# Meta
title: Natalie and Paul wedding
description: Site for the wedding of Natalie and Paul
baseurl: "https://natandpaul.info"
url: "https://natandpaul.info"
permalink: pretty

# Build settings
markdown: kramdown
